### ISSUE TITLE
How to run on Mac M1/M2

### ISSUE THREAD

**Issue by xjose97x** [exercism/development-environment#105]
Has anyone been successful running the project on apple sillicon?

I'm getting the following errors (obtained from docker-compose logs):

```
development-environment-website-1               | server   | Puma starting in single mode...
development-environment-website-1               | server   | * Version 4.3.12 (ruby 3.1.0-p0), codename: Mysterious Traveller
development-environment-website-1               | server   | * Min threads: 5, max threads: 5
development-environment-website-1               | server   | * Environment: development
development-environment-website-1               | server   | * Listening on tcp://0.0.0.0:3020
development-environment-website-1               | server   | Use Ctrl-C to stop
development-environment-website-1               | js       | Browserslist: caniuse-lite is outdated. Please run:
development-environment-website-1               | js       |   npx browserslist@latest --update-db
development-environment-website-1               | js       |   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
development-environment-website-1               | manifest | /usr/local/bundle/gems/rb-inotify-0.10.1/lib/rb-inotify/notifier.rb:69:in `initialize': Function not implemented - Failed to initialize inotify (Errno::ENOSYS)
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/listen-3.0.8/lib/listen/adapter/linux.rb:31:in `new'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/listen-3.0.8/lib/listen/adapter/linux.rb:31:in `_configure'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/listen-3.0.8/lib/listen/adapter/base.rb:45:in `block in configure'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/listen-3.0.8/lib/listen/adapter/base.rb:40:in `each'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/listen-3.0.8/lib/listen/adapter/base.rb:40:in `configure'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/listen-3.0.8/lib/listen/adapter/base.rb:63:in `start'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/listen-3.0.8/lib/listen/backend.rb:28:in `start'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/listen-3.0.8/lib/listen/listener.rb:67:in `block in <class:Listener>'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/listen-3.0.8/lib/listen/fsm.rb:120:in `instance_eval'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/listen-3.0.8/lib/listen/fsm.rb:120:in `call'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/listen-3.0.8/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/listen-3.0.8/lib/listen/fsm.rb:57:in `transition'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/listen-3.0.8/lib/listen/listener.rb:90:in `start'
development-environment-website-1               | manifest | 	from /usr/src/app/bin/monitor-manifest:11:in `<main>'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/commands/runner/runner_command.rb:43:in `perform'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/command/base.rb:87:in `perform'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/command.rb:48:in `invoke'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/commands.rb:18:in `<main>'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
development-environment-website-1               | manifest | 	from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
development-environment-website-1               | manifest | 	from bin/rails:4:in `<main>'
development-environment-website-1               | manifest | Exited
development-environment-website-1               | sidekiq  | W, [2023-04-22T05:16:25.980897 #292]  WARN -- Skylight: [SKYLIGHT] [5.3.2] Running Skylight in development mode. No data will be reported until you deploy your app.
development-environment-website-1               | sidekiq  | (To disable this message for all local apps, run `skylight disable_dev_warning`.)
development-environment-website-1               | server   | Interrupting...
development-environment-website-1               | anycable | Interrupting...
development-environment-website-1               | sidekiq  | Interrupting...
development-environment-website-1               | ws       | Interrupting...
development-environment-website-1               | css      | Interrupting...
development-environment-website-1               | js       | Interrupting...
development-environment-website-1               | ws       |   INFO 2023-04-22T05:16:26.071Z context=main Shutting down... (hit Ctrl-C to stop immediately)
development-environment-website-1               | anycable | /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/journey/route.rb:115:in `to_sym': Interrupt
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/journey/route.rb:115:in `map'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/journey/route.rb:115:in `parts'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/route_set.rb:255:in `initialize'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/route_set.rb:191:in `initialize'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/route_set.rb:175:in `new'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/route_set.rb:175:in `create'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/route_set.rb:113:in `add'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/route_set.rb:594:in `add_route'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:1962:in `add_route'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:1933:in `decomposed_match'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:1902:in `block in map_match'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:1900:in `each'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:1900:in `map_match'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:1639:in `match'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:735:in `map_method'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:688:in `get'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:1473:in `block (3 levels) in resources'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:1862:in `path_scope'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:1506:in `block in collection'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:1742:in `with_scope_level'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:1505:in `collection'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:1472:in `block (2 levels) in resources'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:886:in `controller'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:1750:in `resource_scope'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:1467:in `block in resources'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:1742:in `with_scope_level'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/mapper.rb:1465:in `resources'
development-environment-website-1               | anycable | 	from /usr/src/app/config/routes.rb:385:in `block in <main>'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/route_set.rb:426:in `instance_exec'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/route_set.rb:426:in `eval_block'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_dispatch/routing/route_set.rb:408:in `draw'
development-environment-website-1               | anycable | 	from /usr/src/app/config/routes.rb:4:in `<main>'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/application/routes_reloader.rb:50:in `block in load_paths'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/application/routes_reloader.rb:50:in `each'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/application/routes_reloader.rb:50:in `load_paths'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/application/routes_reloader.rb:24:in `reload!'
development-environment-website-1               | sidekiq  | /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:21:in `before': Interrupt
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:50:in `block in tsort_each_child'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:50:in `select'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:50:in `tsort_each_child'
development-environment-website-1               | sidekiq  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:415:in `call'
development-environment-website-1               | sidekiq  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:415:in `each_strongly_connected_component_from'
development-environment-website-1               | sidekiq  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:50:in `each'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:50:in `tsort_each_child'
development-environment-website-1               | sidekiq  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:415:in `call'
development-environment-website-1               | sidekiq  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:415:in `each_strongly_connected_component_from'
development-environment-website-1               | sidekiq  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
development-environment-website-1               | sidekiq  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
development-environment-website-1               | sidekiq  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
development-environment-website-1               | sidekiq  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
development-environment-website-1               | sidekiq  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
development-environment-website-1               | sidekiq  | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:60:in `run_initializers'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/application.rb:372:in `initialize!'
development-environment-website-1               | sidekiq  | 	from /usr/src/app/config/environment.rb:18:in `<top (required)>'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/cli.rb:273:in `require'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/cli.rb:273:in `boot_application'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/sidekiq-6.4.1/lib/sidekiq/cli.rb:37:in `run'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/sidekiq-6.4.1/bin/sidekiq:31:in `<top (required)>'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/bin/sidekiq:25:in `load'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/bin/sidekiq:25:in `<top (required)>'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `load'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in `run'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in `exec'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/bundler-2.3.7/exe/bundle:48:in `block in <top (required)>'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/gems/bundler-2.3.7/exe/bundle:36:in `<top (required)>'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/bin/bundle:25:in `load'
development-environment-website-1               | sidekiq  | 	from /usr/local/bundle/bin/bundle:25:in `<main>'
development-environment-website-1               | ws       |   INFO 2023-04-22T05:16:26.083Z context=rpc All active RPC calls finished
development-environment-website-1               | server   | - Gracefully stopping, waiting for requests to finish
development-environment-website-1               | server   | === puma shutdown: 2023-04-22 05:16:26 +0000 ===
development-environment-website-1               | server   | - Goodbye!
development-environment-website-1               | server   | Exiting
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/application/routes_reloader.rb:38:in `block in updater'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/activesupport-7.0.2.3/lib/active_support/file_update_checker.rb:83:in `execute'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/application/routes_reloader.rb:13:in `execute'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/application/finisher.rb:156:in `block in <module:Finisher>'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `instance_exec'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `run'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
development-environment-website-1               | anycable | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
development-environment-website-1               | anycable | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
development-environment-website-1               | anycable | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
development-environment-website-1               | anycable | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
development-environment-website-1               | anycable | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
development-environment-website-1               | anycable | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
development-environment-website-1               | anycable | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
development-environment-website-1               | anycable | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
development-environment-website-1               | anycable | 	from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/initializable.rb:60:in `run_initializers'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/railties-7.0.2.3/lib/rails/application.rb:372:in `initialize!'
development-environment-website-1               | anycable | 	from /usr/src/app/config/environment.rb:18:in `<top (required)>'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/anycable-core-1.2.2/lib/anycable/cli.rb:157:in `require'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/anycable-core-1.2.2/lib/anycable/cli.rb:157:in `boot_app!'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/anycable-core-1.2.2/lib/anycable/cli.rb:44:in `run'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/anycable-core-1.2.2/bin/anycable:7:in `<top (required)>'
development-environment-website-1               | anycable | 	from /usr/local/bundle/bin/anycable:25:in `load'
development-environment-website-1               | anycable | 	from /usr/local/bundle/bin/anycable:25:in `<top (required)>'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `load'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in `run'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in `exec'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/bundler-2.3.7/exe/bundle:48:in `block in <top (required)>'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
development-environment-website-1               | anycable | 	from /usr/local/bundle/gems/bundler-2.3.7/exe/bundle:36:in `<top (required)>'
development-environment-website-1               | anycable | 	from /usr/local/bundle/bin/bundle:25:in `load'
development-environment-website-1               | anycable | 	from /usr/local/bundle/bin/bundle:25:in `<main>'
development-environment-website-1               | sidekiq  | Exited
development-environment-website-1               | anycable | Exited
development-environment-website-1               | server   | Exited
development-environment-website-1               | js       | Exited
development-environment-website-1               | ws       | Exited
development-environment-website-1               | css      | Exited
development-environment-website-1 exited with code 1

```

**Comment by iHiD** [comment]
I don't think anyone actually uses this (development-environment) approach anymore to run Exercism locally. What are you trying to achieve?
